### ISSUE TITLE
Response for request to '/task/report/create' was already committed (code=302)

### ISSUE THREAD

**Issue by hello-josh** [GoogleCloudPlatform/appengine-java-vm-runtime#356]
I am upgrading from vm:true to env:flex (via appengine-web.xml) and get the following error on one of my routes.

`WARNING: Response for request to '/task/report/create' was already committed (code=302). This might result in lost log messages.`

I am using the latest version of the appengine maven plugin to deploy, and this is the auto generated `app.yaml` that it creates.

```
runtime: java
env: flex
module: 'report'
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5
threadsafe: True
auto_id_policy: default
beta_settings:
  'enable_app_engine_apis': 'true'
  'source_reference': '11db0552bf47f6f29b22ab9a2ac49c0858c81e44'
health_check:
  enable_health_check: False
  check_interval_sec: 10
resources:
  cpu: 2.0
  memory_gb: 7.0
api_version: '1.0'
handlers:
- url: (/.*/)
  static_files: __static__\1index.html
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
- url: (/)
  static_files: __static__\1index.html
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
- url: (/.*)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
- url: /.*
  script: unused
  login: optional
  secure: optional

skip_files: app.yaml
```

I get a similar error on `/_ah/health` but with a 403. I do not have a handler implemented in my application for that route.
